/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// FIXME: debug why package updates sometimes break and require a service worker unregister
// I wonder if it has something to do with the hashes remaining the same
// Or, how I'm using `version` below
// UPDATE: it looks like it's because index.runtime.<whatever>.js is not in the manifest
// https://github.com/parcel-bundler/parcel/issues/9309

import { clientsClaim } from 'workbox-core';
import { createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';

import { manifest, version } from '@parcel/service-worker';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
precacheAndRoute(manifest.map((url) => ({ url, revision: version })));

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }: { request: Request; url: URL }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith('/_')) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains
    // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL('/index.html'),
);

self.addEventListener('message', async (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    await self.skipWaiting();

    self.clients
      .matchAll({
        includeUncontrolled: true,
        type: 'window',
      })
      .then((clients) => {
        for (const client of clients) {
          client.postMessage({
            type: 'reload_ready',
          });
        }
      });
  }
});

// Any other custom service worker logic can go here.
